### ISSUE TITLE
Linking publications with external media

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/newsletter#22]
Did you know that you don't need to upload media to TACC for linking with publications if it already exists elsewhere?

The New Mexico Museum of Natural History and Science publishes a Bulletin and the University of New Mexico Libraries hosts PDFs of these Bulletins in its New Mexico Digital Collections. Because the entire Bulletin is hosted, there is no need to upload a PDF to TACC, instead I created media with the url of the document

![image](https://user-images.githubusercontent.com/5725767/75098769-8049a280-5577-11ea-8762-d7482ba1a209.png)

then added a description and a relationship to the Arctos publication

![image](https://user-images.githubusercontent.com/5725767/75098777-ac652380-5577-11ea-938c-2095b6a6050a.png)

and now the PDF can be accessed directly from the publication!

![image](https://user-images.githubusercontent.com/5725767/75098813-f5b57300-5577-11ea-970b-f26cacacaf6d.png)

![image](https://user-images.githubusercontent.com/5725767/75098835-32816a00-5578-11ea-87f5-e46b47961d52.png)

The best part is that I didn't have to create a multi-page document and UNM Libraries maintains all of the metadata related to the publication!

![image](https://user-images.githubusercontent.com/5725767/75098849-5775dd00-5578-11ea-9736-1496fc033e94.png)

So the next time you are about to scan a document for upload to TACC, make sure you aren't duplicating effort and make use of existing documents if possible. Look for stable resources such as libraries, BHL, etc.

Happy Linking!!!

**Comment by mkoo** [comment]
is anyone going to file an issue to add that Woo Hoo as a success
response?!!!!!!

**Comment by Jegelewicz** [comment]
I don't know - it is awful RED!

**Comment by sharpphyl** [comment]
I do hope you'll add this to the "how to" section of the Handbook.

**Comment by Jegelewicz** [comment]
Added [here](http://handbook.arctosdb.org/how_to/How-to-Create-a-Publication.html#pro-tip-link-to-existing-media).

**Comment by sharpphyl** [comment]
Thanks!!

**Comment by KyndallH** [comment]
@ewommack

**Comment by ewommack** [comment]
We published the article in the latest newsletter, so I'll close the issue. Thanks @Jegelewicz!
