### ISSUE TITLE
Arctos PG Announcement

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/newsletter#23]
Calling all Arctos Members to Help Test the New Version of Arctos in Postgres!

A test version of the new Arctos is ready for testing. 
What is the new version? So glad you asked! Arctos is moving from Oracle to an all-new open-source software stack (Lucee and PostgreSQL). This new version of Arctos will help us add new features and keep Arctos up to date. However, before we can move Arctos to this new platform we need to make sure that the current features will work correctly.

So we're asking Arctos users from all different collection types to help test and troubleshoot the new platform before our official migration. You can find information about the Postgres migration and testing in the [GitHub repository issues page](https://github.com/ArctosDB/PG-migration-testing).
Not familiar with GitHub? No worries, we've got you covered. Check out this [How To Get Started in GitHub section ](https://handbook.arctosdb.org/how_to/How-to-Use-Github-for-Arctos.html#how-to-get-started-in-github) in the Arctos Handbook.
So test, test, test away! All information on how the test platform handles users and your experience working with it is important and useful.

**Comment by ewommack** [comment]
@dustymc @Jegelewicz Hey guys - what do you think? Anything I should add?

**Comment by dustymc** [comment]
It's great. Here are some links if you want to include them.

https://lucee.org/aboutlucee.html

https://www.postgresql.org/about/

**Comment by Jegelewicz** [comment]
It's awesome! Thank you!!!!

**Comment by ewommack** [comment]
Great!

It's funny...I'm trying to figure out how to add labels to this issue. I know I've done it with the other Arctos GitHub repositories. I can't seem to add them or assign people to this one though. 
I must be doing something wrong.

**Comment by campmlc** [comment]
Maybe you need permissions for this repository?

Mariel Campbell

Collection Manager, Division of Genomic Resources
Museum of Southwestern  Biology

Shipping Address:
Museum of Southwestern Biology
Division of Genomic Resources
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131

(505) 277-7808 office
email: campmlc@unm.edu



________________________________

**Comment by ewommack** [comment]
Maybe that is it! I can't see the little selection squares I would normally use:
<img width="1792" alt="Screen Shot 2020-04-09 at 5 11 35 PM" src="https://user-images.githubusercontent.com/18562884/78948395-5eec3980-7a85-11ea-8955-f45bd174c4fc.png">

@dustymc could you give me permission please?

**Comment by dustymc** [comment]
You should have it (or maybe an email, IDK how github works...).

**Comment by campmlc** [comment]
Who has access to give access for the repositories?
BTW this looks great!

**Comment by ewommack** [comment]
Haha got it @dustymc! Thanks.

I guess I'll keep the issue open until we publish the newsletter.

**Comment by dustymc** [comment]
>access to give access

I still don't know how github works, but at least https://github.com/orgs/ArctosDB/teams/dba/members

**Comment by sharpphyl** [comment]
Got the following after getting a different password and logging in.  

> Your account is locked. Contact your supervisor or the person who manages accounts for your organization for access.

Is the test site limited to AWG or other group?

**Comment by dustymc** [comment]
@sharpphyl I reset your account, you should have email, everyone's welcome, start here: https://github.com/ArctosDB/PG-migration-testing/blob/master/README.md
