### ISSUE TITLE
Arctos Social Distancing

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/newsletter#24]
How to Arctos while Social Distancing
If anyone is trying to keep a student intern (or themselves) working during social distancing, here are some things a student (or you!) could help with:
1. Testing Arctos PG - there are all kinds of needed testing spelled out in the [PG data migration testing GitHub repository issues](https://github.com/ArctosDB/PG-migration-testing/issues). For more information see the article in this Newsletter on Arctos Postgres testing.

2. Help create community connections - Use social media. Create Arctos Data Scavenger Hunts or ask for help finding publications. Come up with some creative ways that all those K-12 kids at home can use Arctos Data. Connect Arctos to iNaturalist - use a specimen to kick off a backyard bug or weed hunt with all observations added to an iNaturalist Project. We could literally have millions of these….

3. Improve the Arctos user experience - Everyone complains about the Arctos Data Entry form. Work with the Arctos API to create a Google Form that mirrors the Arctos Data Entry form without the whole thing on one sheet. Want an example to start with? [Here is a Form](https://docs.google.com/forms/d/1LMj13NvZTWBupCTeISqRV63A3ea9rcmRS1so_jDMX5k/edit?usp=sharing) created by Teresa Mayfield last fall that allowed students to capture trait data from paper catalogs that then could then bulkloaded from the resulting Google Sheet into Arctos - adding all those traits to specimen records already in Arctos. The real challenge will be can the Google Form use the Arctos API to provide the Agents, Taxa, Higher Geography, and various other code tables for selection.

4. Make a short Arctos Tutorial. See what is needed[ here](https://docs.google.com/spreadsheets/d/1BESoZ0mgRgONfSNziHpeumIIlnAWtoOnXxPISgQy2mU/edit#gid=0). Note: this Google Sheet also includes instructions for making tutorials!

5. Georeference! Students don’t need access to shared localities to georeference. [See how Dianna Krejsa at Angelo State is doing it](https://github.com/ArctosDB/data-migration/issues/149#issuecomment-606052089).

6. Social Media: We need someone to help Arctos up its social media presence. Use the “Something Random” stuff to start off with and provide links to Arctos records, projects, agent pages, etc.

7. Increase the quality of your Projects in Arctos: Find the projects you created that are incomplete and flesh them out! The list of low quality projects (project description os less than 100 characters or project does not contribute or use cataloged items) can be found in the .csv in [this GitHub issue](https://github.com/ArctosDB/arctos/issues/2570#issuecomment-608091910).

Have more ideas? Let the us know! We can add your ideas to the [article in the Arctos Handbook](https://handbook.arctosdb.org/how_to/How-To-Arctos-While-Social-Distancing.html).

**Comment by ewommack** [comment]
Does anyone know who wrote the original article? I want to make sure they get credit in the Newsletter.

**Comment by campmlc** [comment]
Teresa . . .
