### ISSUE TITLE
Question on Newsletter repository Intro Page

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/newsletter#27]
The Newsletter Repository Intro says that the table has the links for past Newsletters, but when I click on them they take me to webinars.

I mailchimp list of past newsletters is here:
[https://us17.campaign-archive.com/home/?u=cfe3221343c60fe519031e616&id=bdcc2ad5bb](url)

Is it ok if I change this? I'm not sure why we have the webinars here, but do not want to mess something up.

**Comment by campmlc** [comment]
https://us17.campaign-archive.com/home/?u=cfe3221343c60fe519031e616&id=bdcc2ad5bb

**Comment by ebraker** [comment]
Odd... yes you can change and it shouldn't affect webinars.

**Comment by ewommack** [comment]
Done
